# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='read_url',
            field=models.CharField(blank=True, default=b'', max_length=250, verbose_name=b'source url'),
        ),
    ]
