# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0002_auto_20160712_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='gsheet_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
