# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0003_read_gsheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedsilosfieldmapping',
            name='merge_type',
            field=models.CharField(blank=True, choices=[(b'merge', b'Merge'), (b'append', b'Append')], max_length=60, null=True),
        ),
    ]
