# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0005_anonymizingfields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnonymizingFields',
            new_name='PIIColumn',
        ),
    ]
