# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0006_auto_20160805_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piicolumn',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
