# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0007_auto_20160808_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='read',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
