# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0011_auto_20170207_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='onedrive_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
