# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-15 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silo', '0012_thirdpartytokens_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedSilos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_time', models.DateTimeField()),
                ('silo_name_id', models.CharField(max_length=255)),
                ('silo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
