# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0013_auto_20160406_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='autopush_frequency',
            field=models.CharField(blank=True, choices=[(b'DISABLED', b'Disabled'), (b'daily', b'Daily'), (b'weekly', b'Weekly')], max_length=25, null=True),
        ),
    ]
