# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0014_read_autopush_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='autopull',
        ),
        migrations.AlterField(
            model_name='read',
            name='autopull_frequency',
            field=models.CharField(blank=True, choices=[(b'DISABLED', b'Disabled'), (b'daily', b'Daily'), (b'weekly', b'Weekly')], max_length=25, null=True),
        ),
    ]
