# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-19 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0014_formulacolumnmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedsilos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
