# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0017_silohidefilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.TextField()),
                ('operation', models.TextField()),
                ('column_name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='columnordermapping',
            name='silo',
        ),
        migrations.RemoveField(
            model_name='formulacolumnmapping',
            name='silo',
        ),
        migrations.RemoveField(
            model_name='silohidefilter',
            name='silo',
        ),
        migrations.AddField(
            model_name='silo',
            name='columns',
            field=models.TextField(default=b'[]'),
        ),
        migrations.AddField(
            model_name='silo',
            name='hidden_columns',
            field=models.TextField(default=b'[]'),
        ),
        migrations.AddField(
            model_name='silo',
            name='rows_to_hide',
            field=models.TextField(default=b'[]'),
        ),
        migrations.DeleteModel(
            name='ColumnOrderMapping',
        ),
        migrations.DeleteModel(
            name='FormulaColumnMapping',
        ),
        migrations.DeleteModel(
            name='siloHideFilter',
        ),
        migrations.AddField(
            model_name='silo',
            name='formulacolumns',
            field=models.ManyToManyField(blank=True, related_name='silos', to='silo.FormulaColumn'),
        ),
    ]
