# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0018_auto_20170710_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='autopull_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='read',
            name='autopush_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
