# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0019_merge_20170722_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflowlevel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name=b'Country Name')),
                ('level1_uuid', models.CharField(max_length=255, unique=True, verbose_name=b'WorkflowLevel1 UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name=b'Name')),
                ('activity_id', models.IntegerField(blank=True, verbose_name=b'ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('country',),
                'verbose_name_plural': 'Workflowlevel 1',
            },
        ),
        migrations.CreateModel(
            name='Workflowlevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name=b'Country Name')),
                ('level2_uuid', models.CharField(max_length=255, unique=True, verbose_name=b'WorkflowLevel2 UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name=b'Name')),
                ('activity_id', models.IntegerField(blank=True, verbose_name=b'ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('country',),
                'verbose_name_plural': 'Workflowlevel 2',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='level_1_label',
            field=models.CharField(blank=True, default=b'Program', max_length=255, verbose_name=b'Project/Program Organization Level 1 label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='level_2_label',
            field=models.CharField(blank=True, default=b'Project', max_length=255, verbose_name=b'Project/Program Organization Level 2 label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='level_3_label',
            field=models.CharField(blank=True, default=b'Component', max_length=255, verbose_name=b'Project/Program Organization Level 3 label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='level_4_label',
            field=models.CharField(blank=True, default=b'Activity', max_length=255, verbose_name=b'Project/Program Organization Level 4 label'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silo.Organization'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='workflowlevel1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silo.Workflowlevel1'),
        ),
        migrations.AddField(
            model_name='workflowlevel1',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silo.Organization'),
        ),
    ]
