# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0020_auto_20170726_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlevel1',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silo.Country'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silo.Country'),
        ),
    ]
