# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0019_auto_20170719_1146'),
        ('silo', '0021_auto_20170727_0249'),
    ]

    operations = [
    ]
