# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0022_merge_20170728_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolauser',
            name='tola_user_uuid',
            field=models.CharField(default=b'', max_length=255, verbose_name=b'TolaUser UUID'),
        ),
    ]
