# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0023_tolauser_tola_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_uuid',
            field=models.CharField(default=b'', max_length=255, verbose_name=b'Organization UUID'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='tola_user_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name=b'TolaUser UUID'),
        ),
    ]
