# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    def gen_user_uuid(apps, schema_editor):
        tUser = apps.get_model('silo', 'tolauser')
        for row in tUser.objects.all():
            row.tola_user_uuid = uuid.uuid4()
            row.save()

    def gen_org_uuid(apps, schema_editor):
        tOrg = apps.get_model('silo', 'organization')
        for row in tOrg.objects.all():
            row.organization_uuid = uuid.uuid4()
            row.save()

    dependencies = [
        ('silo', '0032_tolauser_tola_user_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_user_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_org_uuid, reverse_code=migrations.RunPython.noop)
    ]
