# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0037_auto_20171110_0101'),
        ('silo', '0034_tolauser_tola_user_uuid'),
    ]

    operations = [
    ]
