# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('silo', '0039_auto_20171205_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Celery task id')),
                ('task_status', models.CharField(blank=True, choices=[(b'CREATED', b'CREATED'), (b'IN_PROGRESS', b'IN_PROGRESS'), (b'FINISHED', b'FINISHED'), (b'FAILED', b'FAILED')], max_length=25, null=True, verbose_name=b'Celery task status')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
