# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0039_auto_20171205_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='task_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Celery task id'),
        ),
    ]
