# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0039_auto_20171205_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='task_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Celery task id'),
        ),
        migrations.AddField(
            model_name='read',
            name='task_status',
            field=models.CharField(blank=True, choices=[(b'CREATED', b'CREATED'), (b'IN_PROGRESS', b'IN_PROGRESS'), (b'FINISHED', b'FINISHED'), (b'FAILED', b'FAILED')], max_length=25, null=True, verbose_name=b'Celery task status'),
        ),
    ]
