# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0040_auto_20180220_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silo',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
