# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0040_auto_20180125_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='task_status',
            field=models.CharField(blank=True, choices=[(b'CREATED', b'CREATED'), (b'RUNNING', b'RUNNING'), (b'FINISHED', b'FINISHED'), (b'FAILED', b'FAILED')], max_length=25, null=True, verbose_name=b'Celery task status'),
        )
    ]
