# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0041_auto_20180308_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='silo',
            name='form_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'CustomForm UUID'),
        ),
    ]
