# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0042_auto_20180323_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='silo',
            name='share_with_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name=b'Organization UUID'),
        ),
        migrations.AlterField(
            model_name='silo',
            name='workflowlevel1',
            field=models.ManyToManyField(blank=True, to='silo.WorkflowLevel1'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='tola_user_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name=b'TolaUser UUID'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silo.WorkflowLevel1'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='workflowlevel1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silo.WorkflowLevel1'),
        ),
    ]
