# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-31 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('silo', '0011_auto_20170207_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyTokensUsername',
            fields=[
                ('thirdpartytokens_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='silo.ThirdPartyTokens')),
                ('username', models.CharField(max_length=60)),
            ],
            bases=('silo.thirdpartytokens',),
        ),
    ]
