# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-05 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartytokensusername',
            name='thirdpartytokens_ptr',
        ),
        migrations.DeleteModel(
            name='ThirdPartyTokensUsername',
        ),
    ]
