# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-18 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='aggregation_function',
        ),
        migrations.AddField(
            model_name='graphinput',
            name='aggregation_function',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
