# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170118_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphinput',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='graph_inputs', to='board.Item'),
            preserve_default=False,
        ),
    ]
