# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_graphinput_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphinput',
            name='graph_input',
            field=models.CharField(max_length=150),
        ),
    ]
