# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20170125_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='wdiget_row',
            new_name='widget_row',
        ),
    ]
