# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0011_auto_20170207_1051'),
        ('board', '0006_auto_20170131_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardsilo',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('silo.silo',),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='board.Boardsilo'),
        ),
    ]
