# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20170207_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphinput',
            old_name='graphinput',
            new_name='graphmodelvalue',
        ),
        migrations.RemoveField(
            model_name='graphinput',
            name='graph',
        ),
        migrations.AddField(
            model_name='graphinput',
            name='graphmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='graphinputs', to='board.Graphmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphinput',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphinputs', to='board.Item'),
        ),
    ]
