# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 18:58
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('board', '0008_auto_20170215_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='board.Owner'),
        ),
        migrations.AlterField(
            model_name='graphinput',
            name='graphmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphinputs', to='board.Graphmodel'),
        ),
    ]
