# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20170713_0301'),
        ('board', '0010_auto_20170425_0204'),
    ]

    operations = [
    ]
